title: "PolyEdge Documentation"
description: "Documentation for PolyEdge setup and deployment."
remote_theme: pmarsceill/just-the-docs
search_enabled: true
logo: "assets/images/logo_nobg.png" # Relative path without baseurl
title_only_logo: false

# Sidebar settings
show_toc: true
show_toc_sidebar: true
toc_levels: 1..3
color_scheme: dark

baseurl: "/polyedge-docs"
url: "https://tiaminetworks.github.io"

# Exclude unnecessary files from the build
exclude:
  - Gemfile
  - Gemfile.lock
