title: "PolyEdge Documentation"
description: "Documentation for PolyEdge setup and deployment."
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Sidebar settings
show_toc: true
show_toc_sidebar: true
toc_levels: 1..3

# Base URL configuration for GitHub Pages
baseurl: "/polyedge-docs" # If hosted under a subdirectory
url: "https://tiaminetworks.github.io" # Ensure this matches your GitHub Pages URL

just_the_docs:
  custom_css:
    - assets/css/custom.css

# Exclude unnecessary files from the build
exclude:
  - Gemfile
  - Gemfile.lock

# Navigation hierarchy
just_the_docs:
  show_toc: true
  show_toc_sidebar: true
  toc_levels: 1..3
  navigation:
    - title: "Home"
      url: /
      children:
        - title: "Getting Started"
          url: /getting-started/
