title: "PolyEdge Documentation"
description: "Documentation for PolyEdge setup and deployment."
remote_theme: pmarsceill/just-the-docs
search_enabled: true
just_the_docs:
  custom_css:
    - assets/css/custom.css
    
# Sidebar settings
show_toc: true
show_toc_sidebar: true
toc_levels: 1..3


# Base URL configuration for GitHub Pages
baseurl: "polyedge-docs" # Leave blank if hosted at the root (e.g., https://username.github.io)
url: "https://tiaminetworks.github.io" # Replace with your GitHub username
