title: "PolyEdge Documentation"
description: "Documentation for PolyEdge setup and deployment."
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Sidebar settings
show_toc: true
show_toc_sidebar: true
toc_levels: 1..3

# Custom CSS
just_the_docs:
  custom_css:
    - assets/css/custom.css

# Base URL configuration for GitHub Pages
baseurl: "polyedge-docs"
url: "https://tiaminetworks.github.io"

# Exclude unnecessary files from the build
exclude:
  - Gemfile
  - Gemfile.lock
